name: Metrics

on:
  push:
    branches: [ main ]
  schedule:
    # Runs at 12AM JST
    - cron: '00 15 * * *'
  workflow_dispatch:

jobs:
  github-metrics:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # classic for AniList
          user: blacktanktop
          template: classic
          config_gemoji: yes
          config_timezone: Asia/Tokyo
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes

          # # Basic
          # base: header
          # # 本来は以下全てを表示すべき。今回は省略
          # # base: header, activity, community, repositories, metadata
          # repositories_forks: no
          # repositories_affiliations: owner, collaborator
          # repositories_skipped: blacktanktop/blacktanktop

          # AniList
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: characters, watching, reading, favorites
          plugin_anilist_limit: 2 # キャラ以外の同時表示数
          plugin_anilist_shuffle: yes # シャッフル
          plugin_anilist_user: .user.login # ユーザ名がGitHubと揃っている場合はこれでいい
          plugin_anilist_limit_characters: 22 # キャラ上限
          
          # Metrics
          # plugin_reactions: yes
          # plugin_reactions_limit: 200                 # Compute reactions over last 200 issue comments
          # plugin_reactions_days: 14                   # Compute reactions on issue comments posted less than 14 days ago
          # plugin_reactions_details: count, percentage # Display reactions count and percentage
          # plugin_reactions_ignored: bot               # Ignore "bot" user
          plugin_achievements: yes
          plugin_achievements_threshold: C       # Display achievements with rank C or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0           # Display all unlocked achievement matching
          plugin_achievements_display: compact   # Use compact display 
          threshold and secrets params
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}      # Required
          plugin_wakatime_days: 14                                   # Display last 2 week stats
          plugin_wakatime_sections: time, projects, projects-graphs # Display time and projects sections, along with projects graphs
          plugin_wakatime_limit: 4                                  # Show 4 entries per graph
          plugin_wakatime_url: https://wakatime.com                  # Wakatime url endpoint
          plugin_wakatime_user: .user.login                         # User
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
          plugin_topics_mode: mastered # Display icons instead of labels
          plugin_topics_limit: 0       # Disable limitations
